### ISSUE TITLE
Try unifying ingress to a single load balancer?

### ISSUE THREAD

**Issue by Cervator** [Cervator/KubicArk#17]
May make more sense for a variety of reasons:

* Just one IP to worry about, then sequential ports
* Just one service entry in YAML
* Cost for a single LB / IP - although pricing there seems complicated. 

Might be $15-18 per month just for a single LB? That would add up _fast_ if they hang out (to keep the IP the same while a pod is hibernating). Unsure if a single LB with more redirects would just end up charging about the same as several LBs with just 3 rules each.

Attempted an approach using an `lbtype: external` thing I found via Google/LinkedIn: https://www.linkedin.com/pulse/exposing-multiple-portsservices-same-load-balancer-sunil-agarwal/ - but after some rounds of tinkering I couldn't seem to get _two_ ARK servers working at once. 

Testing with a Valguero on defaults and Genesis on a port offset oddly made Genesis work and Valguero fail. Of perhaps note the Genesis service entries were later in the YAML file ... then peculiarly removing the Genesis entries made Valguero work. But then later couldn't replicate.

Going to try just with standalone LBs for now

Approach at the time - central `ark-service.yaml`:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ark-external-lb
spec:
  type: LoadBalancer
  ports:
  # Valguero ports
  - port: 27015
    targetPort: 27015
    protocol: UDP
    name: ark-valg-steam # This supports the Steam server browser
  - port: 7777
    targetPort: 7777
    protocol: UDP
    name: ark-valg-client # This is for regular direct connections?
  - port: 7778
    targetPort: 7778
    protocol: UDP
    name: ark-valg-raw # This should always be client port + 1

  # Genesis part 1 ports
  - port: 27014
    targetPort: 27014
    protocol: UDP
    name: ark-gen1-steam
  - port: 7775
    targetPort: 7775
    protocol: UDP
    name: ark-gen1-client
  - port: 7776
    targetPort: 7776
    protocol: UDP
    name: ark-gen1-raw

  selector:
    # This trick lets us map several deployments to a single service, just varying the ports
    lbtype: external
```

Start of one example deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-genesis
  labels:
    app: ark-genesis
spec:
  replicas: 1
  selector:
    matchLabels:
      lbtype: external
  template:
    metadata:
      labels:
        lbtype: external
        app: ark-genesis
    spec: ...
```
